import { Resend } from 'resend';
import { NextRequest, NextResponse } from 'next/server';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: NextRequest) {
  const { to, subject, report, vesselData } = await request.json();

  if (!to || !report) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
  }

  try {
    const { data, error } = await resend.emails.send({
      from: 'Ghost Fleet Detector <alerts@resend.dev>',
      to: [to],
      subject: subject || `Intelligence Report: Vessel ${vesselData?.mmsi || 'Unknown'}`,
      html: `
        <div style="font-family: 'Courier New', monospace; background: #0a1628; color: #67e8f9; padding: 24px; border-radius: 8px;">
          <div style="border-bottom: 1px solid #164e63; padding-bottom: 16px; margin-bottom: 16px;">
            <h1 style="color: #22d3ee; margin: 0; font-size: 20px;">GHOST FLEET DETECTOR</h1>
            <p style="color: #0891b2; margin: 4px 0 0; font-size: 12px;">MARITIME INTELLIGENCE REPORT</p>
          </div>

          ${vesselData ? `
          <div style="background: #132743; padding: 16px; border-radius: 4px; margin-bottom: 16px; border-left: 3px solid ${
            vesselData.riskLevel === 'CRITICAL' ? '#ff3366' :
            vesselData.riskLevel === 'HIGH' ? '#f97316' :
            vesselData.riskLevel === 'MEDIUM' ? '#eab308' : '#22c55e'
          };">
            <table style="width: 100%; font-size: 12px;">
              <tr>
                <td style="color: #0891b2; padding: 4px 0;">MMSI:</td>
                <td style="color: #22d3ee;">${vesselData.mmsi}</td>
                <td style="color: #0891b2; padding: 4px 0;">Risk Level:</td>
                <td style="color: ${
                  vesselData.riskLevel === 'CRITICAL' ? '#ff3366' :
                  vesselData.riskLevel === 'HIGH' ? '#f97316' :
                  vesselData.riskLevel === 'MEDIUM' ? '#eab308' : '#22c55e'
                }; font-weight: bold;">${vesselData.riskLevel}</td>
              </tr>
              <tr>
                <td style="color: #0891b2; padding: 4px 0;">Dark Period:</td>
                <td style="color: #22d3ee;">${vesselData.gapHours?.toFixed(1) || 'N/A'} hours</td>
                <td style="color: #0891b2; padding: 4px 0;">Score:</td>
                <td style="color: #22d3ee;">${vesselData.suspicionScore}/100</td>
              </tr>
              <tr>
                <td style="color: #0891b2; padding: 4px 0;">Distance:</td>
                <td style="color: #22d3ee;">${vesselData.distanceNm?.toFixed(1) || 'N/A'} nm</td>
                <td style="color: #0891b2; padding: 4px 0;">Implied Speed:</td>
                <td style="color: #22d3ee;">${vesselData.impliedSpeedKnots?.toFixed(1) || 'N/A'} kts</td>
              </tr>
            </table>
          </div>
          ` : ''}

          <div style="background: #132743; padding: 16px; border-radius: 4px; margin-bottom: 16px;">
            <h2 style="color: #22d3ee; margin: 0 0 12px; font-size: 14px;">ANALYSIS</h2>
            <div style="color: #a5f3fc; font-size: 13px; line-height: 1.6; white-space: pre-wrap;">${report}</div>
          </div>

          <div style="font-size: 10px; color: #0891b2; text-align: center; padding-top: 16px; border-top: 1px solid #164e63;">
            Generated by Ghost Fleet Detector • ${new Date().toISOString()}
          </div>
        </div>
      `,
    });

    if (error) {
      console.error('Resend error:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true, id: data?.id });
  } catch (error) {
    console.error('Email send error:', error);
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 });
  }
}
